config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  resources :users
  resources :deductions
  resources :incomes
  resources :session
  get 'main/index'

  root 'main#index'

end

app/models/deduction.rb
class Deduction < ActiveRecord::Base
  belongs_to :user
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  has_many :incomes
  has_many :deductions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deductions_controller.rb
class DeductionsController < ApplicationController
  before_action :set_deduction, only: [:show, :edit, :update, :destroy]

  # GET /deductions
  # GET /deductions.json
  def index
    @deductions = Deduction.all
  end

  # GET /deductions/1
  # GET /deductions/1.json
  def show
  end

  # GET /deductions/new
  def new
    @deduction = Deduction.new
  end

  # GET /deductions/1/edit
  def edit
  end

  # POST /deductions
  # POST /deductions.json
  def create
    @deduction = Deduction.new(deduction_params)

    respond_to do |format|
      if @deduction.save
        format.html { redirect_to @deduction, notice: 'Deduction was successfully created.' }
        format.json { render :show, status: :created, location: @deduction }
      else
        format.html { render :new }
        format.json { render json: @deduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deductions/1
  # PATCH/PUT /deductions/1.json
  def update
    respond_to do |format|
      if @deduction.update(deduction_params)
        format.html { redirect_to @deduction, notice: 'Deduction was successfully updated.' }
        format.json { render :show, status: :ok, location: @deduction }
      else
        format.html { render :edit }
        format.json { render json: @deduction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deductions/1
  # DELETE /deductions/1.json
  def destroy
    @deduction.destroy
    respond_to do |format|
      format.html { redirect_to deductions_url, notice: 'Deduction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deduction
      @deduction = Deduction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deduction_params
      params.fetch(:deduction, {})
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.fetch(:income, {})
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require[:user].permit(:email, :password, :password_confirmation, :password_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deductions_helper.rb
module DeductionsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/deductions/_form.html.erb
<%= form_for(@deduction) do |f| %>
  <% if @deduction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deduction.errors.count, "error") %> prohibited this deduction from being saved:</h2>

      <ul>
      <% @deduction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deductions/edit.html.erb
<h1>Editing Deduction</h1>

<%= render 'form' %>

<%= link_to 'Show', @deduction %> |
<%= link_to 'Back', deductions_path %>

app/views/deductions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deductions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deductions.each do |deduction| %>
      <tr>
        <td><%= link_to 'Show', deduction %></td>
        <td><%= link_to 'Edit', edit_deduction_path(deduction) %></td>
        <td><%= link_to 'Destroy', deduction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deduction', new_deduction_path %>

app/views/deductions/new.html.erb
<h1>New Deduction</h1>

<%= render 'form' %>

<%= link_to 'Back', deductions_path %>

app/views/deductions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_deduction_path(@deduction) %> |
<%= link_to 'Back', deductions_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incomes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><%= link_to 'Show', income %></td>
        <td><%= link_to 'Edit', edit_income_path(income) %></td>
        <td><%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Income', new_income_path %>

app/views/incomes/new.html.erb
<h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAgiPuma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>
<button class="btn btn-primary">THIS IS TEST</button>
This is written in new
I write in new again
WHAT?
<span class="glyphicon glyphicon-plus"></span>
<%= link_to "Incomes", incomes_path %>
<%= link_to "Sign Up", new_user_path %>

app/views/session/new.html.erb
<h1>Session#new</h1>
<p>Find me in app/views/session/new.html.erb</p>

app/views/users/new.html.erb
<!--This is the user sign up form-->
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_message">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <%end%>
      </ul>
    </div>
  <% end %>
  <!--form fields-->
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions"><%=f.submit %></div>
<% end %>